-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 09:44:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mooddb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mooddb` ;

-- -----------------------------------------------------
-- Schema mooddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mooddb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mooddb` ;

-- -----------------------------------------------------
-- Table `mooddb`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mooddb`.`device` ;

CREATE TABLE IF NOT EXISTS `mooddb`.`device` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mooddb`.`moodface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mooddb`.`moodface` ;

CREATE TABLE IF NOT EXISTS `mooddb`.`moodface` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Key` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(45) NULL DEFAULT NULL,
  `Label` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mooddb`.`moodentry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mooddb`.`moodentry` ;

CREATE TABLE IF NOT EXISTS `mooddb`.`moodentry` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `MoodFaceId` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `MoodDeviceId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_MoodEntry_MoodFace_idx` (`MoodFaceId` ASC) VISIBLE,
  INDEX `fk_MoodEntry_MoodDevice1_idx` (`MoodDeviceId` ASC) VISIBLE,
  CONSTRAINT `fk_MoodEntry_MoodDevice1`
    FOREIGN KEY (`MoodDeviceId`)
    REFERENCES `mooddb`.`device` (`Id`),
  CONSTRAINT `fk_MoodEntry_MoodFace`
    FOREIGN KEY (`MoodFaceId`)
    REFERENCES `mooddb`.`moodface` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
